# ref: https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
name: Version Bump Action
description: A simple GitHub Actions to bump the version of projects

author: Nick Nichols

branding:
  color: purple
  icon: git-commit

inputs:
  github-token:
    description: 'A GitHub auth token to be able to create the pull request'
    required: true
  gradle-path:
    description: 'The relative location of your build.gradle file'
    required: false
    default: '.'
  git-author-email:
    description: 'The email address to be used as the author for the release'
    required: false
  git-author-username:
    description: 'The name to be used as the author for the release'
    required: false
  git-committer-email:
    description: 'The email address to be used as the committer for the release'
    required: false
  git-committer-username:
    description: 'The name to be used as the committer for the release'
    required: false

outputs:
  version:
    description: 'The final version (whether updated or not)'
    value: ${{ steps.get-final-version.outputs.version }}
  initial-version:
    description: 'The initial version before the action ran'
    value: ${{ steps.config.outputs.current-version }}

runs:
  using: "composite"
  steps:
    - name: Configure action
      id: config
      shell: bash
      run: |
        if [ -z ${{ inputs.git-author-email }} ]; then 
          echo "git-author-email=${{ github.actor }}@users.noreply.github.com" >> $GITHUB_OUTPUT
        else
          echo "git-author-email=${{ inputs.git-author-email }}" >> $GITHUB_OUTPUT
        fi
        if [ -z ${{ inputs.git-author-email }} ]; then 
          echo "git-author-username=${{ github.actor }}" >> $GITHUB_OUTPUT
        else
          echo "git-author-username=${{ inputs.git-author-username }}" >> $GITHUB_OUTPUT
        fi

        if [ -z ${{ inputs.git-committer-email }} ]; then 
          echo "git-committer-email=bumpVersionBot@users.noreply.github.com" >> $GITHUB_OUTPUT
        else
          echo "git-committer-email=${{ inputs.git-committer-email }}" >> $GITHUB_OUTPUT
        fi
        if [ -z ${{ inputs.git-committer-email }} ]; then 
          echo "git-committer-username=github-actions[bot]" >> $GITHUB_OUTPUT
        else
          echo "git-committer-username=${{ inputs.git-committer-username }}" >> $GITHUB_OUTPUT
        fi

        echo "current-version=$(${{github.action_path}}/get-version.sh)" >> $GITHUB_OUTPUT

    - name: Bump Version
      id: bump
      env:
        TOKEN: ${{ inputs.github-token }}
        GIT_AUTHOR_NAME: ${{ steps.config.outputs.git-author-username }}
        GIT_AUTHOR_EMAIL: ${{ steps.config.outputs.git-author-email }}
        GIT_COMMITTER_NAME: ${{ steps.config.outputs.git-committer-username }}
        GIT_COMMITTER_EMAIL: ${{ steps.config.outputs.git-committer-email }}
        CURRENT_VERSION: ${{ steps.config.outputs.current-version }}
      run: ${{github.action_path}}/version-bump.sh
      shell: bash

    - name: Get final version
      id: get-final-version
      shell: bash
      run: echo "version=$(${{github.action_path}}/get-version.sh)" >> $GITHUB_OUTPUT
